### ISSUE TITLE
trilio-data-mover hook failed: "install" (TypeError: Can't convert 'NoneType' object to str implicitly)

### ISSUE THREAD

**Issue by ryan-beisner** [trilioData/triliovault-cfg-scripts#110]
During deployment, the trilio-data-mover units go into an ERROR state, detailed below.  This is with charms built from master of this repo @ 2c3a5e015c3e0fde9bdbcd8288f31a09962add8b.

This is observed when deploying using the example bundle, and setting the triliovault-ip to our instance of the TV appliance.

```
ubuntu@beisner-bastion:~/git/charm-test-infra$ juju status trilio-data-mover
Model    Controller           Cloud/Region             Version    SLA          Timestamp
beisner  beisner-serverstack  serverstack/serverstack  2.5-beta1  unsupported  21:35:00Z

App                  Version       Status   Scale  Charm                Store       Rev  OS      Charm version  Notes
neutron-openvswitch  12.0.3        blocked      0  neutron-openvswitch  jujucharms  249  ubuntu                 
nova-compute         17.0.5        waiting      3  nova-compute         jujucharms  282  ubuntu                 
ntp                  4.2.8p4+dfsg  active       0  ntp                  jujucharms   24  ubuntu                 
trilio-data-mover                  error        3  trilio-data-mover    local         1  ubuntu  2c3a5e0-dirty  

Unit                      Workload  Agent      Machine  Public address  Ports    Message
nova-compute/0            waiting   executing  14       10.5.0.10                Incomplete relations: image
  neutron-openvswitch/2   blocked   executing           10.5.0.10                (leader-settings-changed) Missing relations: messaging
  ntp/2                   active    executing           10.5.0.10       123/udp  (config-changed) Ready
  trilio-data-mover/2     error     idle                10.5.0.10                hook failed: "install"
nova-compute/1*           waiting   executing  15       10.5.0.16                Incomplete relations: image
  neutron-openvswitch/0*  active    idle                10.5.0.16                Unit is ready
  ntp/0*                  active    idle                10.5.0.16       123/udp  Ready
  trilio-data-mover/0*    error     idle                10.5.0.16                hook failed: "install"
nova-compute/2            waiting   executing  16       10.5.0.8                 Incomplete relations: image
  neutron-openvswitch/1   active    executing           10.5.0.8                 Unit is ready
  ntp/1                   active    executing           10.5.0.8        123/udp  Ready
  trilio-data-mover/1     error     idle                10.5.0.8                 hook failed: "install"

Machine  State    DNS        Inst id                               Series  AZ    Message
14       started  10.5.0.10  b7ddfedb-3418-4d86-accb-6683046385c7  xenial  nova  ACTIVE
15       started  10.5.0.16  a43560d5-8f6b-435c-aab0-dde2adf2cce1  xenial  nova  ACTIVE
16       started  10.5.0.8   b556e85c-d3af-4fe2-9109-f684453fb0b2  xenial  nova  ACTIVE
```

```
2018-10-02 21:26:47 DEBUG install   python3-virtualenv virtualenv
2018-10-02 21:26:48 DEBUG install 0 upgraded, 2 newly installed, 0 to remove and 20 not upgraded.
2018-10-02 21:26:48 DEBUG install Need to get 47.6 kB of archives.
2018-10-02 21:26:48 DEBUG install After this operation, 171 kB of additional disk space will be used.
2018-10-02 21:26:48 DEBUG install Get:1 http://nova.clouds.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 python3-virtualenv all 15.0.1+ds-3ubuntu1 [43.2 kB]
2018-10-02 21:26:48 DEBUG install Get:2 http://nova.clouds.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 virtualenv all 15.0.1+ds-3ubuntu1 [4342 B]
2018-10-02 21:26:48 DEBUG install Fetched 47.6 kB in 0s (146 kB/s)
2018-10-02 21:26:48 DEBUG install Selecting previously unselected package python3-virtualenv.
2018-10-02 21:26:48 DEBUG install (Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 82368 files and directories currently installed.)
2018-10-02 21:26:48 DEBUG install Preparing to unpack .../python3-virtualenv_15.0.1+ds-3ubuntu1_all.deb ...
2018-10-02 21:26:48 DEBUG install Unpacking python3-virtualenv (15.0.1+ds-3ubuntu1) ...
2018-10-02 21:26:48 DEBUG install Selecting previously unselected package virtualenv.
2018-10-02 21:26:48 DEBUG install Preparing to unpack .../virtualenv_15.0.1+ds-3ubuntu1_all.deb ...
2018-10-02 21:26:48 DEBUG install Unpacking virtualenv (15.0.1+ds-3ubuntu1) ...
2018-10-02 21:26:48 DEBUG install Processing triggers for man-db (2.7.5-1) ...
2018-10-02 21:26:48 DEBUG install Setting up python3-virtualenv (15.0.1+ds-3ubuntu1) ...
2018-10-02 21:26:49 DEBUG install Setting up virtualenv (15.0.1+ds-3ubuntu1) ...
2018-10-02 21:26:50 DEBUG install Already using interpreter /usr/bin/python3
2018-10-02 21:26:50 DEBUG install Using base prefix '/usr'
2018-10-02 21:26:50 DEBUG install New python executable in /var/lib/juju/agents/unit-trilio-data-mover-0/.venv/bin/python3
2018-10-02 21:26:50 DEBUG install Also creating executable in /var/lib/juju/agents/unit-trilio-data-mover-0/.venv/bin/python
2018-10-02 21:26:50 DEBUG install Please make sure you remove any previous custom paths from your /root/.pydistutils.cfg file.
2018-10-02 21:26:52 DEBUG install Installing setuptools, pkg_resources, pip, wheel...done.
2018-10-02 21:26:53 DEBUG install Ignoring indexes: https://pypi.python.org/simple
2018-10-02 21:26:53 DEBUG install Collecting pip
2018-10-02 21:26:53 DEBUG install Building wheels for collected packages: pip
2018-10-02 21:26:53 DEBUG install   Running setup.py bdist_wheel for pip: started
2018-10-02 21:26:54 DEBUG install   Running setup.py bdist_wheel for pip: finished with status 'done'
2018-10-02 21:26:54 DEBUG install   Stored in directory: /root/.cache/pip/wheels/8d/a1/f1/9bb4decbb5c137d43b9b321d84b234011a771da51a81984ed9
2018-10-02 21:26:54 DEBUG install Successfully built pip
2018-10-02 21:26:54 DEBUG install Installing collected packages: pip
2018-10-02 21:26:54 DEBUG install   Found existing installation: pip 8.1.1
2018-10-02 21:26:54 DEBUG install     Uninstalling pip-8.1.1:
2018-10-02 21:26:54 DEBUG install       Successfully uninstalled pip-8.1.1
2018-10-02 21:26:55 DEBUG install Successfully installed pip-8.1.2
2018-10-02 21:26:56 DEBUG install Ignoring indexes: https://pypi.python.org/simple
2018-10-02 21:26:56 DEBUG install Collecting setuptools
2018-10-02 21:26:56 DEBUG install Collecting setuptools-scm
2018-10-02 21:26:56 DEBUG install Building wheels for collected packages: setuptools, setuptools-scm
2018-10-02 21:26:56 DEBUG install   Running setup.py bdist_wheel for setuptools: started
2018-10-02 21:26:57 DEBUG install   Running setup.py bdist_wheel for setuptools: finished with status 'done'
2018-10-02 21:26:57 DEBUG install   Stored in directory: /root/.cache/pip/wheels/96/22/d9/f290f7e4ac98e1b64678c1885d25577b218c3e83db223bfc85
2018-10-02 21:26:57 DEBUG install   Running setup.py bdist_wheel for setuptools-scm: started
2018-10-02 21:26:57 DEBUG install   Running setup.py bdist_wheel for setuptools-scm: finished with status 'done'
2018-10-02 21:26:57 DEBUG install   Stored in directory: /root/.cache/pip/wheels/d8/93/b1/638c6f0608620427531c4b034a5ee13df12666b83ec34140c6
2018-10-02 21:26:57 DEBUG install Successfully built setuptools setuptools-scm
2018-10-02 21:26:57 DEBUG install Installing collected packages: setuptools, setuptools-scm
2018-10-02 21:26:57 DEBUG install   Found existing installation: setuptools 20.7.0
2018-10-02 21:26:57 DEBUG install     Uninstalling setuptools-20.7.0:
2018-10-02 21:26:57 DEBUG install       Successfully uninstalled setuptools-20.7.0
2018-10-02 21:26:58 DEBUG install Successfully installed setuptools-39.0.1 setuptools-scm-1.17.0
2018-10-02 21:26:58 DEBUG install Ignoring indexes: https://pypi.python.org/simple
2018-10-02 21:26:58 DEBUG install Processing ./wheelhouse/netaddr-0.7.19.tar.gz
2018-10-02 21:26:59 DEBUG install Processing ./wheelhouse/pyaml-17.12.1.tar.gz
2018-10-02 21:26:59 DEBUG install Processing ./wheelhouse/six-1.11.0.tar.gz
2018-10-02 21:27:00 DEBUG install Processing ./wheelhouse/setuptools_scm-1.17.0.tar.gz
2018-10-02 21:27:00 DEBUG install Processing ./wheelhouse/PyYAML-3.13.tar.gz
2018-10-02 21:27:00 DEBUG install Processing ./wheelhouse/charms.reactive-1.1.1.tar.gz
2018-10-02 21:27:01 DEBUG install Processing ./wheelhouse/Jinja2-2.10.tar.gz
2018-10-02 21:27:01 DEBUG install Processing ./wheelhouse/pip-8.1.2.tar.gz
2018-10-02 21:27:02 DEBUG install Processing ./wheelhouse/charmhelpers-0.19.2.tar.gz
2018-10-02 21:27:02 DEBUG install Processing ./wheelhouse/boto-2.49.0.tar.gz
2018-10-02 21:27:03 DEBUG install Processing ./wheelhouse/Tempita-0.5.2.tar.gz
2018-10-02 21:27:03 DEBUG install Processing ./wheelhouse/MarkupSafe-1.0.tar.gz
2018-10-02 21:27:04 DEBUG install Processing ./wheelhouse/setuptools-39.0.1.zip
2018-10-02 21:27:04 DEBUG install Collecting PyYAML (from pyaml==17.12.1)
2018-10-02 21:27:05 DEBUG install Collecting charmhelpers>=0.5.0 (from charms.reactive==1.1.1)
2018-10-02 21:27:05 DEBUG install Collecting MarkupSafe>=0.23 (from Jinja2==2.10)
2018-10-02 21:27:05 DEBUG install Collecting Tempita (from charmhelpers==0.19.2)
2018-10-02 21:27:06 DEBUG install Building wheels for collected packages: netaddr, pyaml, PyYAML, six, setuptools-scm, charms.reactive, charmhelpers, Jinja2, MarkupSafe, pip, Tempita, boto, setuptools
2018-10-02 21:27:06 DEBUG install   Running setup.py bdist_wheel for netaddr: started
2018-10-02 21:27:07 DEBUG install   Running setup.py bdist_wheel for netaddr: finished with status 'done'
2018-10-02 21:27:07 DEBUG install   Stored in directory: /root/.cache/pip/wheels/25/06/85/9d475a42d1bfd40518bfc2c1443bed664689de999ef184d764
2018-10-02 21:27:07 DEBUG install   Running setup.py bdist_wheel for pyaml: started
2018-10-02 21:27:07 DEBUG install   Running setup.py bdist_wheel for pyaml: finished with status 'done'
2018-10-02 21:27:07 DEBUG install   Stored in directory: /root/.cache/pip/wheels/97/08/47/25ed199b96e4de05b1a39e9dbba52730eaa4fcdde16fce5023
2018-10-02 21:27:07 DEBUG install   Running setup.py bdist_wheel for PyYAML: started
2018-10-02 21:27:07 DEBUG install   Running setup.py bdist_wheel for PyYAML: finished with status 'done'
2018-10-02 21:27:07 DEBUG install   Stored in directory: /root/.cache/pip/wheels/e4/41/d9/ebb2aa122a3c98bff27fb762c6c65a1af9552dd8a38f6ab5a8
2018-10-02 21:27:07 DEBUG install   Running setup.py bdist_wheel for six: started
2018-10-02 21:27:08 DEBUG install   Running setup.py bdist_wheel for six: finished with status 'done'
2018-10-02 21:27:08 DEBUG install   Stored in directory: /root/.cache/pip/wheels/4d/0e/97/dcd4ffc74f3e13330da26307a7d692fb41e60187d7d92bbaa5
2018-10-02 21:27:08 DEBUG install   Running setup.py bdist_wheel for setuptools-scm: started
2018-10-02 21:27:08 DEBUG install   Running setup.py bdist_wheel for setuptools-scm: finished with status 'done'
2018-10-02 21:27:08 DEBUG install   Stored in directory: /root/.cache/pip/wheels/d8/93/b1/638c6f0608620427531c4b034a5ee13df12666b83ec34140c6
2018-10-02 21:27:08 DEBUG install   Running setup.py bdist_wheel for charms.reactive: started
2018-10-02 21:27:09 DEBUG install   Running setup.py bdist_wheel for charms.reactive: finished with status 'done'
2018-10-02 21:27:09 DEBUG install   Stored in directory: /root/.cache/pip/wheels/6b/63/f6/6cb3bdc9e968b9487d377c27fb21ed4f46fad841dc9d21be33
2018-10-02 21:27:09 DEBUG install   Running setup.py bdist_wheel for charmhelpers: started
2018-10-02 21:27:09 DEBUG install   Running setup.py bdist_wheel for charmhelpers: finished with status 'done'
2018-10-02 21:27:09 DEBUG install   Stored in directory: /root/.cache/pip/wheels/fc/69/f5/a1c5559ffa61e91f9cb78152f88e786cdcb422a971350464eb
2018-10-02 21:27:09 DEBUG install   Running setup.py bdist_wheel for Jinja2: started
2018-10-02 21:27:10 DEBUG install   Running setup.py bdist_wheel for Jinja2: finished with status 'done'
2018-10-02 21:27:10 DEBUG install   Stored in directory: /root/.cache/pip/wheels/59/2e/d6/59209afcc9c7f6c05787bc3ae31c0e3a30412125ddd5a0dc4f
2018-10-02 21:27:10 DEBUG install   Running setup.py bdist_wheel for MarkupSafe: started
2018-10-02 21:27:10 DEBUG install   Running setup.py bdist_wheel for MarkupSafe: finished with status 'done'
2018-10-02 21:27:10 DEBUG install   Stored in directory: /root/.cache/pip/wheels/38/62/51/956275a599dc548a69a3f7f8ce1c93e2eba0d128b8cf8fc512
2018-10-02 21:27:10 DEBUG install   Running setup.py bdist_wheel for pip: started
2018-10-02 21:27:11 DEBUG install   Running setup.py bdist_wheel for pip: finished with status 'done'
2018-10-02 21:27:11 DEBUG install   Stored in directory: /root/.cache/pip/wheels/8d/a1/f1/9bb4decbb5c137d43b9b321d84b234011a771da51a81984ed9
2018-10-02 21:27:11 DEBUG install   Running setup.py bdist_wheel for Tempita: started
2018-10-02 21:27:13 DEBUG install   Running setup.py bdist_wheel for Tempita: finished with status 'done'
2018-10-02 21:27:13 DEBUG install   Stored in directory: /root/.cache/pip/wheels/9f/e7/d4/ea0caec363c8fc0b4ce450e194ba3fdcd4cdff58a2f5b32597
2018-10-02 21:27:13 DEBUG install   Running setup.py bdist_wheel for boto: started
2018-10-02 21:27:14 DEBUG install   Running setup.py bdist_wheel for boto: finished with status 'done'
2018-10-02 21:27:14 DEBUG install   Stored in directory: /root/.cache/pip/wheels/41/63/b6/6960dfada4014c2c0741328163b934aaf03d798189b14acc30
2018-10-02 21:27:14 DEBUG install   Running setup.py bdist_wheel for setuptools: started
2018-10-02 21:27:15 DEBUG install   Running setup.py bdist_wheel for setuptools: finished with status 'done'
2018-10-02 21:27:15 DEBUG install   Stored in directory: /root/.cache/pip/wheels/96/22/d9/f290f7e4ac98e1b64678c1885d25577b218c3e83db223bfc85
2018-10-02 21:27:15 DEBUG install Successfully built netaddr pyaml PyYAML six setuptools-scm charms.reactive charmhelpers Jinja2 MarkupSafe pip Tempita boto setuptools
2018-10-02 21:27:15 DEBUG install Installing collected packages: netaddr, PyYAML, pyaml, six, setuptools-scm, Tempita, MarkupSafe, Jinja2, charmhelpers, charms.reactive, pip, boto, setuptools
2018-10-02 21:27:15 DEBUG install   Found existing installation: netaddr 0.7.18
2018-10-02 21:27:15 DEBUG install     Not uninstalling netaddr at /usr/lib/python3/dist-packages, outside environment /var/lib/juju/agents/unit-trilio-data-mover-0/.venv
2018-10-02 21:27:15 DEBUG install   Found existing installation: PyYAML 3.12
2018-10-02 21:27:15 DEBUG install     Not uninstalling pyyaml at /usr/lib/python3/dist-packages, outside environment /var/lib/juju/agents/unit-trilio-data-mover-0/.venv
2018-10-02 21:27:15 DEBUG install   Found existing installation: six 1.10.0
2018-10-02 21:27:15 DEBUG install     Not uninstalling six at /usr/lib/python3/dist-packages, outside environment /var/lib/juju/agents/unit-trilio-data-mover-0/.venv
2018-10-02 21:27:15 DEBUG install   Found existing installation: setuptools-scm 1.17.0
2018-10-02 21:27:15 DEBUG install     Uninstalling setuptools-scm-1.17.0:
2018-10-02 21:27:15 DEBUG install       Successfully uninstalled setuptools-scm-1.17.0
2018-10-02 21:27:15 DEBUG install   Found existing installation: MarkupSafe 0.23
2018-10-02 21:27:15 DEBUG install     Not uninstalling markupsafe at /usr/lib/python3/dist-packages, outside environment /var/lib/juju/agents/unit-trilio-data-mover-0/.venv
2018-10-02 21:27:15 DEBUG install   Found existing installation: Jinja2 2.8
2018-10-02 21:27:15 DEBUG install     Not uninstalling jinja2 at /usr/lib/python3/dist-packages, outside environment /var/lib/juju/agents/unit-trilio-data-mover-0/.venv
2018-10-02 21:27:15 DEBUG install   Found existing installation: pip 8.1.2
2018-10-02 21:27:15 DEBUG install     Uninstalling pip-8.1.2:
2018-10-02 21:27:15 DEBUG install       Successfully uninstalled pip-8.1.2
2018-10-02 21:27:17 DEBUG install   Found existing installation: setuptools 39.0.1
2018-10-02 21:27:17 DEBUG install     Uninstalling setuptools-39.0.1:
2018-10-02 21:27:17 DEBUG install       Successfully uninstalled setuptools-39.0.1
2018-10-02 21:27:18 DEBUG install Successfully installed Jinja2-2.10 MarkupSafe-1.0 PyYAML-3.13 Tempita-0.5.2 boto-2.49.0 charmhelpers-0.19.2 charms.reactive-1.1.1 netaddr-0.7.19 pip-8.1.2 pyaml-17.12.1 setuptools-39.0.1 setuptools-scm-1.17.0 six-1.11.0
2018-10-02 21:27:18 INFO juju-log Reactive main running for hook install
2018-10-02 21:27:18 ERROR juju-log Unable to find implementation for relation: requires of rabbitmq
2018-10-02 21:27:19 ERROR juju-log Unable to find implementation for relation: provides of data-mover
2018-10-02 21:27:19 ERROR juju-log Unable to find implementation for relation: requires of juju-info
2018-10-02 21:27:19 INFO juju-log Invoking reactive handler: reactive/trilio_data_mover.py:507:install_tvault_contego_plugin
2018-10-02 21:27:19 DEBUG install PING 10.245.162.159 (10.245.162.159) 56(84) bytes of data.
2018-10-02 21:27:19 DEBUG install 64 bytes from 10.245.162.159: icmp_seq=1 ttl=62 time=3.89 ms
2018-10-02 21:27:19 DEBUG install 
2018-10-02 21:27:19 DEBUG install --- 10.245.162.159 ping statistics ---
2018-10-02 21:27:19 DEBUG install 1 packets transmitted, 1 received, 0% packet loss, time 0ms
2018-10-02 21:27:19 DEBUG install rtt min/avg/max/mdev = 3.899/3.899/3.899/0.000 ms
2018-10-02 21:27:19 INFO juju-log Making dir /var/triliovault-mounts nova:nova 765
2018-10-02 21:27:19 ERROR juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-trilio-data-mover-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-trilio-data-mover-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-trilio-data-mover-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-trilio-data-mover-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-trilio-data-mover-0/charm/reactive/trilio_data_mover.py", line 526, in install_tvault_contego_plugin
    if not validate_backup():
  File "/var/lib/juju/agents/unit-trilio-data-mover-0/charm/reactive/trilio_data_mover.py", line 150, in validate_backup
    return validate_nfs()
  File "/var/lib/juju/agents/unit-trilio-data-mover-0/charm/reactive/trilio_data_mover.py", line 107, in validate_nfs
    if not mount(device, data_dir, filesystem='nfs'):
  File "/var/lib/juju/agents/unit-trilio-data-mover-0/.venv/lib/python3.5/site-packages/charmhelpers/core/host.py", line 585, in mount
    subprocess.check_output(cmd_args)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'NoneType' object to str implicitly

2018-10-02 21:27:19 DEBUG install Traceback (most recent call last):
2018-10-02 21:27:19 DEBUG install   File "/var/lib/juju/agents/unit-trilio-data-mover-0/charm/hooks/install", line 22, in <module>
2018-10-02 21:27:19 DEBUG install     main()
2018-10-02 21:27:19 DEBUG install   File "/var/lib/juju/agents/unit-trilio-data-mover-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
2018-10-02 21:27:19 DEBUG install     bus.dispatch(restricted=restricted_mode)
2018-10-02 21:27:19 DEBUG install   File "/var/lib/juju/agents/unit-trilio-data-mover-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 390, in dispatch
2018-10-02 21:27:19 DEBUG install     _invoke(other_handlers)
2018-10-02 21:27:19 DEBUG install   File "/var/lib/juju/agents/unit-trilio-data-mover-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 359, in _invoke
2018-10-02 21:27:19 DEBUG install     handler.invoke()
2018-10-02 21:27:19 DEBUG install   File "/var/lib/juju/agents/unit-trilio-data-mover-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 181, in invoke
2018-10-02 21:27:19 DEBUG install     self._action(*args)
2018-10-02 21:27:19 DEBUG install   File "/var/lib/juju/agents/unit-trilio-data-mover-0/charm/reactive/trilio_data_mover.py", line 526, in install_tvault_contego_plugin
2018-10-02 21:27:19 DEBUG install     if not validate_backup():
2018-10-02 21:27:19 DEBUG install   File "/var/lib/juju/agents/unit-trilio-data-mover-0/charm/reactive/trilio_data_mover.py", line 150, in validate_backup
2018-10-02 21:27:19 DEBUG install     return validate_nfs()
2018-10-02 21:27:19 DEBUG install   File "/var/lib/juju/agents/unit-trilio-data-mover-0/charm/reactive/trilio_data_mover.py", line 107, in validate_nfs
2018-10-02 21:27:19 DEBUG install     if not mount(device, data_dir, filesystem='nfs'):
2018-10-02 21:27:19 DEBUG install   File "/var/lib/juju/agents/unit-trilio-data-mover-0/.venv/lib/python3.5/site-packages/charmhelpers/core/host.py", line 585, in mount
2018-10-02 21:27:19 DEBUG install     subprocess.check_output(cmd_args)
2018-10-02 21:27:19 DEBUG install   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
2018-10-02 21:27:19 DEBUG install     **kwargs).stdout
2018-10-02 21:27:19 DEBUG install   File "/usr/lib/python3.5/subprocess.py", line 693, in run
2018-10-02 21:27:19 DEBUG install     with Popen(*popenargs, **kwargs) as process:
2018-10-02 21:27:19 DEBUG install   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
2018-10-02 21:27:19 DEBUG install     restore_signals, start_new_session)
2018-10-02 21:27:19 DEBUG install   File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
2018-10-02 21:27:19 DEBUG install     restore_signals, start_new_session, preexec_fn)
2018-10-02 21:27:19 DEBUG install TypeError: Can't convert 'NoneType' object to str implicitly
2018-10-02 21:27:19 ERROR juju.worker.uniter.operation runhook.go:115 hook "install" failed: exit status 1
```

**Comment by ryan-beisner** [comment]
The charm should go into a blocked state when the required charm configuration is not present, instead of crashing to an error state.

**Comment by ryan-beisner** [comment]
After setting the ```backup-target-type``` value to s3, the charm adequately blocks in a state of ```Invalid Backup target type, please provide valid info```, which is OK because I didn't give it a real s3 credential yet.

However, the initial error state still needs to be addressed.  The charm should either default to nfs or s3, or go into a blocked state if the user doesn't specify.

**Comment by MuralidharB** [comment]
Yes, we will take care of it.

**Comment by abhijeetpatra** [comment]
Working on it.

**Comment by abhijeetpatra** [comment]
Raised a PR #112

**Comment by abhijeetpatra** [comment]
PR #112 merged
